// Generated by `node scripts/i18n.mjs types` from the French files. Do not edit.

import type Format from "./messages/fr/Format.json";
import type Native from "./messages/fr/Native.json";
import type Settings from "./messages/fr/Settings.json";

export type Messages = {
  Format: typeof Format;
  Native: typeof Native;
  Settings: typeof Settings;
};
