/**
 * Keeps the translations in order.
 *
 *   node scripts/i18n.mjs types   rewrites src/i18n/messages-types.ts from
 *                                 the French files, so `t("…")` is checked
 *   node scripts/i18n.mjs check   fails when a language misses a key the
 *                                 French has, has one it lacks, or a message
 *                                 is not valid ICU
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parse } from "@formatjs/icu-messageformat-parser";

const ROOT = new URL("../src/i18n/", import.meta.url).pathname;
const DIR = join(ROOT, "messages");
const REFERENCE = "fr";

const locales = readdirSync(DIR).sort();
const namespaces = (locale) =>
  readdirSync(join(DIR, locale))
    .filter((file) => file.endsWith(".json"))
    .map((file) => file.slice(0, -5))
    .sort();
const read = (locale, namespace) =>
  JSON.parse(readFileSync(join(DIR, locale, `${namespace}.json`), "utf8"));

function flatten(tree, prefix = "", out = new Map()) {
  for (const [key, value] of Object.entries(tree)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (value && typeof value === "object") flatten(value, path, out);
    else out.set(path, value);
  }
  return out;
}

function types() {
  const names = namespaces(REFERENCE);
  const lines = [
    "// Generated by `node scripts/i18n.mjs types` from the French files. Do not edit.",
    "",
    ...names.map((name) => `import type ${name} from "./messages/fr/${name}.json";`),
    "",
    "export type Messages = {",
    ...names.map((name) => `  ${name}: typeof ${name};`),
    "};",
    "",
  ];
  writeFileSync(join(ROOT, "messages-types.ts"), lines.join("\n"));
  console.log(`messages-types.ts: ${names.length} namespaces`);
}

function check() {
  const problems = [];
  const reference = new Map(
    namespaces(REFERENCE).map((name) => [name, flatten(read(REFERENCE, name))]),
  );

  for (const locale of locales) {
    const present = new Set(namespaces(locale));
    for (const [name, keys] of reference) {
      if (!present.has(name)) {
        problems.push(`${locale}: missing namespace ${name}`);
        continue;
      }
      const own = flatten(read(locale, name));
      for (const key of keys.keys()) {
        if (!own.has(key)) problems.push(`${locale}: missing ${name}.${key}`);
      }
      for (const [key, value] of own) {
        if (!keys.has(key)) problems.push(`${locale}: extra ${name}.${key}`);
        if (typeof value !== "string") {
          problems.push(`${locale}: ${name}.${key} is not a string`);
          continue;
        }
        try {
          parse(value);
        } catch (error) {
          problems.push(`${locale}: ${name}.${key} is not valid ICU (${error.message})`);
        }
      }
    }
    for (const name of present) {
      if (!reference.has(name)) problems.push(`${locale}: namespace ${name} has no French`);
    }
  }

  if (problems.length) {
    console.error(problems.join("\n"));
    console.error(`\n${problems.length} problem(s)`);
    process.exit(1);
  }
  console.log(`translations: ${locales.join(", ")} agree on ${reference.size} namespaces`);
}

const command = process.argv[2];
if (command === "types") types();
else if (command === "check") check();
else {
  console.error("usage: node scripts/i18n.mjs types|check");
  process.exit(2);
}
